source 'http://rubygems.org'

gem 'github-pages'
gem 'html-proofer'
gem 'jekyll'
gem 'rake'
gem 'rouge'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'jekyll-seo-tag'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-last-modified-at'
gem 'jekyll-admin'
